if: tag IS present OR type = pull_request OR (branch = master AND type = push)   # we only CI the master, tags and PRs
language: python

sudo: false

addons:
  apt:
    packages:
      - graphviz

install:
    pip install tox

script: tox

matrix:
  include:
    - env: TOXENV=py27
      python: 2.7
    - env: TOXENV=py34
      python: 3.4
    - env: TOXENV=py35
      python: 3.5
    - env: TOXENV=py36
      python: 3.6
    - env: TOXENV=py37
      python: 3.7
      dist: xenial
      sudo: true
    - env: TOXENV=py38
      python: 3.8-dev
      dist: xenial
      sudo: true
    - env: TOXENV=lint
      python: 3.6

deploy:
  provider: pypi
  user: prmtl
  password:
    secure: P1Nv54dQUOY+sXAWKkyfkHdhDvziCS3U/6As/NgfKEHCfY6fnZZJzylDuzbJ13foGaQniUa2+InuxoUFsH21YRBaif3PXUlTAJEiseWC3cr0E7DiicnDQB0fWqGS0MT2lQa29H34WVPrxnckt9Hy1whAJYAbBIixbHQrDB22G+U=
  distributions: "sdist bdist_wheel" # Your distributions here
  on:
    python: 3.7
    tags: true
