# Appveyor, continuous integration for Windows
# Most of the config comes from:
# * https://github.com/nedbat/coveragepy/blob/master/appveyor.yml
# * https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml

version: '{branch}-{build}'

shallow_clone: true

cache:
  - '%LOCALAPPDATA%\pip\Cache'

branches:
  only:
  - master

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

environment:

  CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci\\run_with_env.cmd"

  # Parallel pytest gets tangled up with tests that try to create and destroy
  # .pth files in the shared virtualenv. Disable parallel tests.
  PYTEST_ADDOPTS: "-n 0"

  matrix:
    - JOB: "2.7 32-bit"
      TOXENV: "py27"
      PYTHON: "C:\\Python27.11"
      PYTHON_ARCH: "32"

    - JOB: "3.6 64-bit"
      TOXENV: "py36"
      PYTHON: "C:\\Python36-x64"
      PYTHON_ARCH: "64"

init:
  - "ECHO %TOXENV%"

install:
  - cinst graphviz
  # Prepend Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

   # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "python -m pip install --upgrade pip"
  - "python -m pip install --upgrade tox"

build: off

test_script:
  - tox
